// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
uint Width;
uint Height;
RWStructuredBuffer<int> Data;

[numthreads(8, 8, 1)] void CSMain(uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    if (id.x > Width || id.y > Height)
    {
        return;
    }
    float4 color = float4(0, 0, 0, 1.0);
    if (Data[id.y * Width + id.x] == 1)
    {
        color = float4(1, 0.85, 0.47, 1.0);
    }
    else if (Data[id.y * Width + id.x] == 2)
    {
        color = float4(1, 1, 1, 1.0);
    }
    Result[id.xy] = color;
}
